spring:
  h2:
    console:
      path: /h2
      settings:
        web-allow-others: false
      enabled: true
  datasource:
    url: jdbc:h2:file:~/test
    username: sa
    password:
    driverClassName: org.h2.Driver